#!/bin/bash --init-file
<<Block
xrandr --delmode HDMI-1 &&/ "lilP" #for lack of if statement
xrandr --rmmode "lilP"
xrandr --newmode "lilP"  124.88  1872 1968 2168 2464  1091 1092 1095 1120  -HSync +Vsync
xrandr --addmode HDMI-1 "lilP"
xrandr --output HDMI-1 --rotate normal &&\
xrandr --output HDMI-1 --mode lilP
Block
sleep 5
xdotool mousemove 1000 1000
sed -i s/size=../size=28/ ~/.Xresources
xrdb ~/.Xresources
i3-msg split h
urxvt -hold -e bash -c "x11vnc -usepw -display :0 -forever" &
urxvt -hold -e bash -c "cd ~/PaperTTY/ && poetry run papertty --driver EPD3in7 --nopartial vnc --display 0 --password asdf --sleep 0 --rotate 270" &
i3-msg move workspace 9 #creating urxvts in workspace 9 didn't work. Moving them is "correct" approach
sleep 9
i3-msg move workspace 9
i3-msg move workspace 9
sleep 2
urxvt
